import type { Metadata } from "next";
import { Eyebrow } from "@/components/site-shell";

export const metadata: Metadata = { title: "Contact", description: "Talk to TNOTL about protecting your home, school or property." };

export default function ContactPage() {
  return <main className="inner-page contact-page">
    <section className="contact-intro"><Eyebrow>Contact / Get protected</Eyebrow><h1>Tell us about<br /><em>the space.</em></h1><p>Start with what you need to protect. We&apos;ll help you think through the relevant entry points, visibility and response needs.</p><div className="contact-meta"><span>General enquiries</span><a href="mailto:hello@tnotl.com">hello@tnotl.com</a></div></section>
    <section className="contact-form-section"><form className="contact-form" action="mailto:hello@tnotl.com" method="post" encType="text/plain"><div className="field"><label htmlFor="name">Your name</label><input id="name" name="name" autoComplete="name" required placeholder="Full name" /></div><div className="field"><label htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="email" required placeholder="you@company.com" /></div><div className="field"><label htmlFor="organization">Organisation</label><input id="organization" name="organization" autoComplete="organization" placeholder="Optional" /></div><fieldset><legend>Space to protect</legend><div className="choice-grid">{["Home", "School", "Commercial", "Other facility"].map((label) => <label key={label}><input type="checkbox" name="space" value={label} /><span>{label}</span></label>)}</div></fieldset><div className="field"><label htmlFor="message">What should we know?</label><textarea id="message" name="message" required rows={5} placeholder="Tell us about the property, entry points and your current security setup." /></div><button className="button button-light" type="submit">Send enquiry <span aria-hidden="true">↗</span></button><p className="form-note">Submitting opens your email application with the enquiry details.</p></form><aside><span>I</span><h2>One conversation.<br /><em>A clearer plan.</em></h2><p>No generic package assumptions. We begin with the environment and the people inside it.</p></aside></section>
  </main>;
}
